#!/bin/bash
# xKOR_3RR0R — Hyprland deployment config
# Place in ~/.config/hypr/hyprland.conf.d/xkor.conf
# OR add to ~/.config/hypr/hyprland.conf via: source = ~/.config/hypr/hyprland.conf.d/xkor.conf

# --- xKOR_3RR0R Hyprland Configuration ---
# This file is auto-generated by xKOR installer.
# Version: 1.0.0 — Compatible with Hyprland v0.55+

# Window rules for xKOR Tauri app
windowrulev2 = fullscreen, class:(xkor-3rr0r)
windowrulev2 = noborder, class:(xkor-3rr0r)
windowrulev2 = nofocus, class:(xkor-3rr0r)
windowrulev2 = noanim, class:(xkor-3rr0r)
windowrulev2 = keepaspectratio, class:(xkor-3rr0r)
windowrulev2 = focusonactivate, class:(xkor-3rr0r)

# Force xKOR to open on workspace 1, fullscreen
windowrulev2 = workspace 1, class:(xkor-3rr0r)

# Autostart xKOR on Hyprland launch
exec-once = /opt/xkor_3rr0r/src-tauri/target/release/xkor-3rr0r

# Prevent other windows from covering xKOR
windowrulev2 = pin, class:(xkor-3rr0r)
windowrulev2 = stayfocused, class:(xkor-3rr0r)

# Input config for cyberpunk feel
input {
    kb_layout = us
    follow_mouse = 0
    touchpad {
        natural_scroll = true
        tap-to-click = false
    }
}

# General look
general {
    gaps_in = 0
    gaps_out = 0
    border_size = 0
    col.active_border = 0x00000000
    col.inactive_border = 0x00000000
    cursor_inactive_timeout = 5
    no_cursor_warps = true
    allow_tearing = true
}

# Decoration — none (xKOR handles its own look)
decoration {
    rounding = 0
    blur = false
    drop_shadow = false
    shadow_range = 0
    shadow_render_power = 0
    col.shadow = 0x00000000
}

# Animations — disabled for performance
animations {
    enabled = false
}

# No dwindle pseudotile (removed in v0.55+)
# Pseudotiling is now handled per-window via windowrulev2

# xKOR specific env
env = XDG_CURRENT_DESKTOP,xKOR_3RR0R
env = XDG_SESSION_DESKTOP,xKOR_3RR0R
env = XDG_SESSION_TYPE,wayland
